### ISSUE TITLE
Help to connect extended open ai conversion to ha-gpt4vision

### ISSUE THREAD

**Issue by The-Erf** [valentinfrlch/ha-gpt4vision#2]
Hello, I want when we are talking with voice assistant (extended open ai conversion)
I say a certain sentence, for example: What do you see in the camera?
This happens:
1- My automation or script is executed
2- A photo is taken from the camera I specified
3-Then I send that photo to ha-gpt4vision
4- The response of ha-gpt4vision is converted to sound with tts
I have given more detailed explanations here :
https://github.com/jekalmin/extended_openai_conversation/issues/219
Because I have just met the world of home assistant
Should I have done the same or did I go wrong?
The following is very limited and a script or automation must be defined for each request
For example, one with this prompt: analyze everything you see in the picture
Another one with this prompt:
Explain the working of what you see in the picture
Is there an easier way to do all the requests without automation or scripting?
For example, like this:
How many people do you see on the camera?
Or what is the color of their clothes?
Do they look suspicious?

**Comment by valentinfrlch** [comment]
Please understand that this isn't the home assistant forum. If you need help setting up your automations, please ask for help in the dedicated channels. Also, the enhancement label is meant for feature requests.
That said, you can
1. Capture a snapshot on your camera
2. Pass it to `gpt4vision.Image_analyzer`
3. Pass gpt4vision's response to a tts service
Using the following example script (you will need to modify this to fit your specifics):
```yaml
alias: Example
sequence:
  - service: camera.snapshot
    metadata: {}
    data:
      filename: >-
        /config/www/tmp/f51fbdc6f87267b1346efccc796dd6c450ff71b66ec5e795921d442a0305a0ac.jpg
    target:
      entity_id: camera.front_door
  - service: gpt4vision.image_analyzer
    metadata: {}
    data:
      max_tokens: 100
      model: gpt-4o
      target_width: 1280
      image_file: >-
        /config/www/tmp/f51fbdc6f87267b1346efccc796dd6c450ff71b66ec5e795921d442a0305a0ac.jpg
      message: Your promt here
    response_variable: response
  - service: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.entity_id
      message: "{{response.response_text}}"
    target:
      entity_id: tts.piper
```
